version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: musicgraph
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: musicgraph
    restart: always